### ISSUE TITLE
README could use ops information 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/dice-server-js#3]
The readme could use the following items to help document how to operate this dice server:
- overview of the repo contents and how it fits in with the rest of the system
- compile and build
- test locally
- deploy
- restart
- check status (is it alive?)
- check logs

(readme audit ticket where we discussed what should be in each readme: https://github.com/triplea-game/triplea/issues/3289)

**Comment by RoiEXLab** [comment]
Well in order for this dice server to be used it would need to have all core features working first.
See #1 for more information.
I won't have the time to work on this (or any other stuff) during the next 3 weeks, but I recall the core verification process was already working, so all that needs to be done is the user interface and email related logic to use it.

**Comment by DanVanAtta** [comment]
Thanks for response, no problem @RoiEXLab . I'm okay with this being a placeholder/reminder for when we can get around to this, whenever that is. The list of things to include I think is the really valuable thing to remember.
